# Generated by Django 4.2.16 on 2024-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Child Boy'), ('G', 'Child Girl'), ('O', 'Other')], default='O', max_length=1)),
                ('size', models.CharField(blank=True, max_length=3)),
                ('color', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('stock', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
